src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name = '';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @var UploadedFile
     *
     * @Assert\Image()
     */
    private $file;

    /**
     * @var ?string
     *
     * Chemin de l'ancien fichier en cas de modification
     */
    private $oldPath;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get the value of file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Set the value of file.
     *
     * @param UploadedFile $file
     *
     * @return self
     */
    public function setFile(UploadedFile $file)
    {
        $this->oldPath = $this->path; // enregistre le path avant de le mettre à vide pour supprimer l'ancien fichier lors de l'upload
        $this->path = ''; // Modifie le path pour forcer Doctrine à faire la requête et uploader le nouveau fichier
        $this->file = $file;

        return $this;
    }

    /**
     * Retourne l'emplacement des fichiers.
     */
    public function getPublicRootDir()
    {
        return __DIR__.'/../../public/uploads/images/';
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function generatePath()
    {
        if ($this->file instanceof UploadedFile) {
            // Génére le chemin (nom) du fichier à uploader, guessExtension retourne l'extension du fichier uploadé
            $this->path = uniqid('img_').'.'.$this->file->guessExtension();
            // path à img_154a854f8ds6d9.png
            $this->name = $this->file->getClientOriginalName();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Supprime l'ancien fichier s'il existe
        if (is_file($this->getPublicRootDir().$this->oldPath)) {
            unlink($this->getPublicRootDir().$this->oldPath);
        }

        // Test si $file est bien du bon type
        if ($this->file instanceof UploadedFile) {
            // Déplace le fichier uploadé var le dossier uploads
            $this->file->move($this->getPublicRootDir(), $this->path);
        }
    }

    /**
     * @ORM\PreRemove()
     */
    public function remove()
    {
        // Test si le fichier existe
        if (is_file($this->getPublicRootDir().$this->path)) {
            unlink($this->getPublicRootDir().$this->path);
        }
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * Retourne le lien pour afficher l'image (peut être inclus dans une balise img).
     */
    public function getWebPath()
    {
        if (strpos($this->path, 'http') !== false) {
            return $this->path;
        } 
        return '/uploads/images/'.$this->path;
    }
}

src/Entity/Step.php
<?php

namespace App\Entity;

use App\Repository\StepRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StepRepository::class)
 */
class Step
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Ordre;

    /**
     * @ORM\Column(type="text")
     */
    private $Step;

    /**
     * @ORM\ManyToOne(targetEntity=Recipe::class, inversedBy="step")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipe;

    public function __toString()
    {
        return (string) $this->getStep();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdre(): ?int
    {
        return $this->Ordre;
    }

    public function setOrdre(int $Ordre): self
    {
        $this->Ordre = $Ordre;

        return $this;
    }

    public function getStep(): ?string
    {
        return $this->Step;
    }

    public function setStep(string $Step): self
    {
        $this->Step = $Step;

        return $this;
    }

    public function getRecipe(): ?Recipe
    {
        return $this->recipe;
    }

    public function setRecipe(?Recipe $recipe): self
    {
        $this->recipe = $recipe;

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'label' => 'Name :',
                'attr' => ['placeholder' => 'Name'],
            ])

            ->add('image', ImageType::class, ['label' => false])

            ->add('deleteImage', CheckboxType::class, [
                'label' => 'Delete image :',
                'required' => false,
            ])

            ->add('time', null, [
                'label' => 'Prepare time :',
                'attr' => ['placeholder' => 'Prepare time'],
            ])

            ->add('recipeIngredients', CollectionType::class, [
                'label' => 'Ingredients :',
                'entry_type' => RecipeIngredientType::class, 
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'prototype'    => true,
                'required'     => false,
                'by_reference' => false,
            ])

            ->add('step', CollectionType::class, [
                'label' => 'Steps :',
                'entry_type' => StepType::class, 
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'prototype'    => true,
                'required'     => false,
                'by_reference' => false,
            ])

            ->add('meals', CollectionType::class, [
                'label' => 'Meals :',
                'entry_type' => MealType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'prototype'    => true,
                'required'     => false,
                'by_reference' => false,
            ])

            // ->add('save', SubmitType::class, ['label' => 'save'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Ingredient;
use App\Entity\Meal;
use App\Entity\Recipe;
use App\Entity\RecipeIngredient;
use App\Entity\Step;
use App\Form\NewRecipeType;
use App\Form\RecipeType;
use App\Repository\IngredientRepository;
use App\Repository\MealRepository;
use App\Repository\RecipeRepository;
use App\Service\Spoonacular;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Contracts\Translation\TranslatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/index/{page}", requirements = {"page" : "\d+"}, defaults = {"page" : 1})
     */
    public function index(Request $request, RecipeRepository $repository, int $page): Response
    {
        $search = $request->query->get('search', '');

        $countPerPage = 15;

        if (empty($search)) {
            $recipes = $repository->findAll($page, $countPerPage);
        } else {
            $recipes = $repository->findBySearch($search, $page, $countPerPage);
        }

        $nbPages = ceil($recipes->count() / $countPerPage);

        return $this->render('recipe/index.html.twig', ['recipes' => $recipes, 'page' => $page, 'nbPages' => $nbPages]);
    }

    /**
     * @Route("/{id}", requirements = {"id": "\d+"})
     */
    public function show(Recipe $recipe)
    {
        // Pour afficher une entité on va toujours faire un findOneById du repository de l'entité
        return $this->render('recipe/show.html.twig', ['recipe' => $recipe]);
    }

    /**
     * @Route("/new", name="recipe_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(NewRecipeType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /*$entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('recipe.new.success', ['%title%' => $recipe->getName()]));
            */
            $formData = $form->getData();
            $search = $formData['name']; // Récupére la donnée du champ 'name'
            return $this->redirectToRoute('recipe_suggest', ['search' => $search]);
        }

        return $this->render('recipe/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/suggest/{search}", name="recipe_suggest")
     */
    public function suggest(string $search, Spoonacular $spoonacular)
    {
        $result = $spoonacular->search($search);

        return $this->render('recipe/suggest.html.twig', ['results' => $result['results']]);
    }

    /**
     * @Route("/add/{apiId}", name="recipe_add", methods={"GET","POST"}, requirements={"apiId": "\d+"}, defaults={"apiId":0})
     */
    public function add(
        Request $request,
        EntityManagerInterface $entityManager,
        TranslatorInterface $translator,
        Spoonacular $spoonacular,
        $apiId,
        IngredientRepository $ingredientRepository,
        MealRepository $mealRepository
    ): Response
    {
        $recipe = (new Recipe)
            ->setUser($this->getUser())
        ;

        if ($apiId > 0) { // Choisi une recette dans l'api
            $apiRecipe = $spoonacular->searchById($apiId);
            $recipe->setName($apiRecipe['title']);
            $image = (new Image)
                ->setPath($apiRecipe['image'])
            ;
            $recipe->setImage($image);
            $recipe->setTime($apiRecipe['readyInMinutes']);

            // Steps
            $steps = $apiRecipe['analyzedInstructions'][0]['steps'];
            foreach ($steps as $key => $step) {
                $stepEntity = (new Step)
                    ->setStep($step['step'])
                    ->setOrdre($key +1)
                ;

                $recipe->addStep($stepEntity);
            }

            // Ingredients
            $ingredients = $apiRecipe['extendedIngredients'];
            $ingredientList = [];
            foreach ($ingredients as $ingredient) {
                $ingredientList[$ingredient['name']] = [
                    'amount' =>$ingredient['amount'],
                    'unit' => $ingredient['unit'],
                ];
            }
            // Requête pour chercher les ingrédients
            $ingredientEntities = $ingredientRepository->findByList($ingredientList);

            foreach ($ingredientEntities as $ingredientEntity) {
                $recipeIngredient = (new RecipeIngredient)
                    ->setIngredient($ingredientEntity)
                    ->setQuantity($ingredientList[$ingredientEntity->getName()]['amount'])
                ;

                // Supprime l'ingrédient déjà en db de la liste
                unset($ingredientList[$ingredientEntity->getName()]);

                $recipe->addRecipeIngredient($recipeIngredient);
            }

            foreach ($ingredientList as $name => $ingredient) {
                $ingredientEntity = (new Ingredient)
                    ->setName($name)
                    ->setUnit($ingredient['unit'])
                ;

                $entityManager->persist($ingredientEntity);
                
                $recipeIngredient = (new RecipeIngredient)
                    ->setIngredient($ingredientEntity)
                    ->setQuantity($ingredientList[$name]['amount'])
                ;

                $recipe->addRecipeIngredient($recipeIngredient);
            }

            // Meals
            $meals = $apiRecipe['dishTypes'];
            $mealList = [];
            foreach ($meals as $meal) {
                $mealList[] = $meal;
            }
            // Requête pour chercher les meals
            $mealEntities = $mealRepository->findByList($mealList);

            foreach ($mealEntities as $mealEntity) {
                // Supprime le meal déjà en db de la liste
                unset($mealList[array_search($mealEntity->getName(), $mealList)]);

                $recipe->addMeal($mealEntity);
            }

            foreach ($mealList as $mealName) {
            $mealEntity = (new Meal)
                ->setName($mealName)
            ;

            $entityManager->persist($mealEntity);

            $recipe->addMeal($mealEntity);
            }

            $entityManager->flush();

        }

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('recipe.new.success', ['%title%' => $recipe->getName()]));
            
            return $this->redirectToRoute('app_recipe_show', ['id' => $recipe->getId()]);        }

        return $this->render('recipe/add.html.twig', [
            'form' => $form->createView(),
            'recipe' => $recipe,
        ]);
    }

    /**
     * @Route("/{id}/edit", requirements = {"id": "\d+"})
     */
    public function edit(Request $request, EntityManagerInterface $entityManager, TranslatorInterface $translator, Recipe $recipe): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipe->setUser($this->getUser());
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('recipe.edit.success', ['%title%' => $recipe->getName()]));

            return $this->redirectToRoute('app_recipe_index');
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", requirements = {"id": "\d+"})
     */
    public function delete(Request $request, EntityManagerInterface $entityManager, Recipe $recipe): Response
    {
        // Crée un formulaire directement dans le controller
        $form = $this->createFormBuilder()
            ->add('delete', SubmitType::class, ['label' => 'Supprimer'])
            ->getForm()
        ;
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->remove($recipe);
            $entityManager->flush();
            $this->addFlash('success', 'Recette supprimée');

            return $this->redirectToRoute('accueil');
        }
        return $this->render('recipe/_delete_form.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(), ]
        );
    }
}

templates/recipe/_delete_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <h1>Supprimer une recette</h1>

    {{ form_start(form) }}
    {% embed 'decorators/_card.html.twig' with {"class": "border-danger"} %}
    {% block body %}
        <p>Confirmer la suppression de la recette "{{ recipe.name }}".</p>
    {% endblock %}

    {% block footer %}
        {{ form_widget(form.delete, {'attr': {'class': 'btn btn-danger'}}) }}
        <a href="{{ path('app_recipe_index') }}" class="btn btn-secondary">Annuler</a>
    {% endblock %}

    {% endembed %}
    {{ form_end(form) }}
</div>

{% endblock body %}

templates/recipe/_form.html.twig
<div class="container">
    {{ form_start(form) }}
 
        {{ form_row(form.name) }}
            <div class="media mb-3">
                {% if recipe is defined %}
                {# asset permet de pointer sur le dossier 'public', twig appelle la méthode 'getWebPath' de l'image #}
                <img src="{{ recipe.image.webPath }}" class="align-left-center mr-3" style="max-width:180px"/>
                {% endif %}
                <div class="media-body">
                    {{ form_row(form.image) }}
                    {{ form_row(form.deleteImage) }}
                </div>
            </div>
        {{ form_row(form.time) }}
        {{ form_label(form.recipeIngredients) }}
         <div>
            <ul id="tag-field-list"
                data-prototype="{{ form_widget(form.recipeIngredients.vars.prototype)|e }}"
                data-widget-tags="{{ '<li></li>'|e }}"
                data-widget-counter="{{ form.recipeIngredients|length }}"
                class="list-unstyled">
            {% for recipeIngredient in form.recipeIngredients %}
                <li class="d-flex align-items-center">
                    <div class="flex-grow-1">
                    {{ form_errors(recipeIngredient) }}
                    {{ form_widget(recipeIngredient) }}
                    </div>
                    <button type="button" class="btn btn-danger align-self-baseline ml-1" data-delete>⚊</button>
                </li>
            {% endfor %}
            </ul>

            <ul id="tag-field-list"
                data-prototype="{{ form_widget(form.step.vars.prototype)|e }}"
                data-widget-tags="{{ '<li></li>'|e }}"
                data-widget-counter="{{ form.step|length }}"
                class="list-unstyled">
            {% for step in form.step %} 
                 <li class="d-flex align-items-center">
                    <div class="flex-grow-1">
                    {{ form_errors(step) }}
                    {{ form_widget(step) }}
                    </div>
                    <button type="button" class="btn btn-danger align-self-baseline ml-1" data-delete>⚊</button>
                </li>
            {% endfor %}
            </ul>
        </div> 
         {{ form_label(form.meals) }} 
         <div>
            <ul id="tag-field-list"
                data-prototype="{{ form_widget(form.meals.vars.prototype)|e }}"
                data-widget-tags="{{ '<li></li>'|e }}"
                data-widget-counter="{{ form.meals|length }}"
                class="list-unstyled">
            {% for meal in form.meals %}
                <li class="d-flex align-items-center">
                    <div class="flex-grow-1">
                    {{ form_errors(meal) }}
                    {{ form_widget(meal) }}
                    </div>
                    <button type="button" class="btn btn-danger align-self-baseline ml-1" data-delete>⚊</button>
                </li>
            {% endfor %}
            </ul>
        </div>
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/recipe/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Save'}) }}

    <button class="btn btn-primary" href="{{ path('app_recipe_index') }}">back to list</button>
</div>
{% endblock %}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <div class="page-recipes">
    
        <div class="row">
            <div class="col-4">
                <img src="https://cdn.pixabay.com/photo/2016/10/10/01/58/donut-1727498_960_720.png" alt="cake" width="280" height="288"></img>
            </div>
            <div class="col-8">
               <h1>Toutes les recettes</h1>
            </div>
        </div>
</div>
<div class="page-recipes2">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.id }}</td>
                <td>{{ recipe.name }}</td>
                <td>{{ recipe.dateCreate ? recipe.dateCreate|date('d-m-Y H:i') : '' }}</td>
                <td>
                    <a href="{{ path('app_recipe_edit', {'id': recipe.id}) }}" class="btn btn-secondary"><i class="fas fa-edit"></i></a>
                    <a href="{{ path('app_recipe_delete', {'id': recipe.id}) }}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Oups c'est bien vide ici...</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}

    <div class="page-newstep"> 
        <div class="row">
            <div class="col-4">
                <img src="https://cdn.pixabay.com/photo/2019/12/13/11/22/chocolate-4692748_960_720.jpg" alt="cake" width="315" height="216"></img>
            </div>
            <div class="col-8">
                <div class="card" style="width: 30rem;">
                    <div class="card-title">
                        <h1>Rechercher une recette</h1>
                    </div>
                    <div class="card-body">
                        {{ form(form) }}
                        <a href="{{ path('step_index') }}">Retour à la liste des recettes ↩️</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
<div class="page-show">
    
        <div class="row">
            <div class="col-4">
                <img src="https://cdn.pixabay.com/photo/2017/08/07/12/42/fork-2603466_960_720.jpg" alt="cake" width="192" height="288"></img>
            </div>
            <div class="col-8">
            <h1>{{ recipe.name }}</h1>
            </div>
        </div>
</div>

<div class="page-show2">
    <div class="container">
        <div class="row">
            <div class="col">
                <p> Modified {{ recipe.dateCreate ? recipe.dateCreate|date('d/m/Y') : '' }} </p>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <h2> Preparation time : {{ recipe.time }} min </h2>
                <div class="card">
                <h2>Ingredients :</h2>
                {% for recipeIngredient in recipe.recipeIngredients %}
                    <p>{{ recipeIngredient.quantity }} {{ recipeIngredient.ingredient.unit }} of {{ recipeIngredient.ingredient.name }}</p>
                {% endfor %}
            </div>
            </div>
            <div class="col-8">
                {% for steps in recipe.step %}
                    <h2>Step {{ steps.ordre }} :</h2>
                    <p>{{ steps }}</p>
                {% endfor %}
            </div>
        </div>
        <a href="{{ path('app_recipe_index') }}" class="btn-primary">back to list</a>
    </div>
</div>
{% endblock %}

templates/recipe/suggest.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <div class="page-recipes">
    
        <div class="row">
            <div class="col-4">
                <img src="https://cdn.pixabay.com/photo/2016/10/10/01/58/donut-1727498_960_720.png" alt="cake" width="280" height="288"></img>
            </div>
            <div class="col-8">
               <h1>Toutes les recettes trouvées</h1>
            </div>
        </div>
</div>
<div class="page-recipes2">
    
    {% for recipe in results %}
        <div class=" card row no-gutters bg-light position-relative">
            <div class="col-md-6 position-static p-4 pl-md-0">
                <h5 class="mt-0">{{ recipe.title }}</h5>
                <p> Preparation time : {{ recipe.readyInMinutes }} </p>
                <p> Number of persons : {{ recipe.servings }} </p>
                <a href="{{ path('recipe_add', {'apiId': recipe.id}) }}" class="stretched-link">Go to the recipe</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}